---
- name: My environment
  hosts: localhost
  become: false
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    - name: Install packages
      become: true
      block:
        - name: Ensure packages are present [RedHat]
          when: "ansible_facts['distribution'] == 'RedHat'"
          ansible.builtin.dnf:
            name: "{{ packages }}"
            state: present

        - name: Ensure packages are present [Ubuntu]
          when: "ansible_facts['distribution'] == 'Ubuntu'"
          ansible.builtin.apt:
            name: "{{ packages }}"
            state: present

    - name: Ensure directory exists
      loop: "{{ vim_paths }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory

    - name: Ensure vim config files are present
      loop: "{{ vim_config_files }}"
      ansible.builtin.copy:
        src: "{{ item['src'] }}"
        dest: "{{ item['dest'] }}"
        force: true

