---
- name: My environment
  hosts: "{{ my_host | default('localhost') }}"
  become: false
  gather_facts: true
  vars_files:
    - vars.yml
  tasks:
    - name: Install packages
      become: true
      block:
        - name: Ensure packages are present [RedHat]
          when: "ansible_facts['distribution'] == 'RedHat'"
          ansible.builtin.dnf:
            name: "{{ packages }}"
            state: present

        - name: Ensure packages are present [Ubuntu]
          when: "ansible_facts['distribution'] == 'Ubuntu'"
          ansible.builtin.apt:
            name: "{{ packages }}"
            state: present

    - name: Ensure vim directories exist
      loop: "{{ vim_paths }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory

    - name: Ensure vim config files are present
      loop: "{{ vim_config_files }}"
      ansible.builtin.copy:
        src: "{{ item['src'] }}"
        dest: "{{ item['dest'] }}"
        force: true

    - name: Ensure tmux config file is present
      ansible.builtin.copy:
        src: "{{ tmux_config_file['src'] }}"
        dest: "{{ tmux_config_file['dest'] }}"
        force: true

    - name: Ensure vim plugins are present
      ansible.builtin.command: "/usr/bin/vim -c 'PlugInstall --sync' -c ':qa'"

    - name: Ensure tmux config is loaded
      ansible.builtin.command: "/usr/bin/tmux source-file {{ tmux_config_file['dest'] }}"

