---
- name: My environment
  hosts: localhost
  become: false
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure directory exists
      loop: "{{ vim_paths }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory

    - name: Ensure vim config files are present
      loop: "{{ vim_config_files }}"
      ansible.builtin.copy:
        src: "{{ item['src'] }}"
        dest: "{{ item['dest'] }}"

  
