" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

"-- Plugins
call plug#begin('~/.vim/plugins')

Plug 'Yggdroot/indentLine'
Plug 'jvirtanen/vim-hcl'

call plug#end()

source ~/.vim/general/main.vim  " Load General Config

